title: "Remote theme example"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
logo: "http://www.ndclab.com/wp-content/uploads/2020/05/NDCLabWebLogo.png"

# Footer content
footer_content: "Copyright"