title: "Neural Dynamics of Control Laboratory"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false

# Heading anchors
heading_anchors: true

# Logo
logo: "http://www.ndclab.com/wp-content/uploads/2020/05/NDCLabWebLogo.png"

# Footer content
footer_content: "Copyright &copy; 2020 Neural Dynamics of Control Laboratory"
git_edit_repository: "https://github.com/NDCLab/wiki"