# name: Schedule HPC Status Check
# jobs:
#  build:
#  steps:
#    - name: Schedule hpc checks
#      uses: cardinalby/schedule-job-action@v1
#      with:
#        ghToken: ${{ secrets.GH_TOKEN }}
#        templateYmlFile: '.github/workflows/hpc-status.yml'